/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package danielp;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aran
 */
public class EMProveedor extends javax.swing.JFrame {
   AdPro adpro;
    DefaultTableModel model =  new DefaultTableModel();
    int id=0, tel=0;
    String name="",dir;
    
    /** Creates new form EMProveedor */
    public EMProveedor(AdPro adpro) {
        initComponents();
        this.adpro = adpro;
        model.addColumn("ID Proveedor");
        model.addColumn("Nombre");
        model.addColumn("Direccion");
        model.addColumn("Telefono");
        jTable1.setModel(model);
        refresh();
        this.setVisible(true);
        this.setTitle("Eliminar/ Modificar Proveedor");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Eliminar Producto");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Precio Venta", "Precio Compra", "Cantidad"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Estas Seguro de eliminar este Proveedor?");
        if(x==0 && id>0){
            if(delete(id)){
                JOptionPane.showMessageDialog(this, "Se elimino");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "No se elimino");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        name = jTable1.getValueAt(fila, 1).toString();
        dir=jTable1.getValueAt(fila, 2).toString();
        tel = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        
        System.out.println("ID:"+id+" Nombre "+name+" tel: "+tel+" dir "+dir);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adpro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int fila = jTable1.getSelectedRow();
        id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        name = jTable1.getValueAt(fila, 1).toString();
        dir=jTable1.getValueAt(fila, 2).toString();
        tel = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        int x = JOptionPane.showConfirmDialog(this, "Estas Seguro de Actualizar este Proveedor?");
        if(x==0 && id>0){

            ProveedorC p = new ProveedorC(id, name, dir, tel);
            if(update(p)){
                JOptionPane.showMessageDialog(this, "Se actualizo");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "No se actualizo");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public ArrayList<ProveedorC> read(){
    conexion c  = new conexion();
    ArrayList<ProveedorC> lista = new ArrayList<>();

      try {
            String sql = "SELECT * FROM proveedor";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
            ProveedorC p= new ProveedorC(rs.getInt("idProveedor"), rs.getString("nombre"), rs.getString("direccion"),rs.getInt("telefono"));
            lista.add(p);
            }
            ps.close();
            ps=null;
            c.desconectar();
      } catch (Exception e) {
          System.out.println("Fallo metodo");
      }
      return lista;
  
  
  }
    
    public void refresh(){
      while(model.getRowCount()>0){
          model.removeRow(0);
      }
      ArrayList<ProveedorC> lista= read();
      for (ProveedorC p: lista) {
          Object item[]= new Object[4];
          item[0]=p.getId();
          item[1]=p.getNombre();
          item[2]=p.getDireccion();
          item[3]=p.getTel();
          
          model.addRow(item);
        
      }
  
        jTable1.setModel(model);
  
  }
    
    public boolean delete(int id){
        conexion c = new conexion();
        try {
            String sql= "DELETE FROM proveedor  WHERE idProveedor=?";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ps.setInt(1, id);
            ps.execute();
            ps.close();
            ps=null;
            c.desconectar();
            return true;
        } catch (Exception e) {
            return false;
        }
    
    }
    
    public boolean update(ProveedorC p){
        conexion c = new conexion();
        try {
            String sql= "UPDATE proveedor SET nombre=?, direccion=?,telefono=? WHERE idProveedor=?";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ps.setString(1, p.getNombre());
            ps.setString(2, p.getDireccion());
            ps.setDouble(3, p.getTel());
            ps.setInt(4, p.getId());
            ps.execute();
            ps.close();
            ps=null;
            c.desconectar();
            return true;
        } catch (Exception e) {
            return false;
        }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
