/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danielp;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aran
 */
public class eProd extends javax.swing.JFrame {
    AdP adp;
    DefaultTableModel model =  new DefaultTableModel();
    int id=0;
    int cantidad=0;
    String name="";
    double pc, pv;
    int fila;
    /**
     * Creates new form eProd
     */
    public eProd(AdP adp) {
        initComponents();
        this.adp = adp;
        model.addColumn("ID Producto");
        model.addColumn("Nombre");
        model.addColumn("Precio Venta");
        model.addColumn("Precio Compra");
        model.addColumn("Cantidad");
        jTable1.setModel(model);
        refresh();
        this.setVisible(true);
        this.setTitle("Eliminar/ Modificar Producto");
    }

    public boolean delete(int id){
        conexion c = new conexion();
        try {
            String sql= "DELETE FROM producto WHERE idProducto=?";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ps.setInt(1, id);
            ps.execute();
            ps.close();
            ps=null;
            c.desconectar();
            return true;
        } catch (Exception e) {
            return false;
        }
    
    }
    
    public boolean update(productoC p){
        conexion c = new conexion();
        try {
            String sql= "UPDATE producto SET nombre=?, precioVenta=?,precioCompra=?,cantidad=? WHERE idProducto=?";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ps.setString(1, p.getNombre());
            ps.setDouble(2, p.getPrecioVenta());
            ps.setDouble(3, p.getPrecioCompra());
            ps.setDouble(4, p.getCantidad());
            ps.setInt(5, p.getProducto());
            ps.execute();
            ps.close();
            ps=null;
            c.desconectar();
            return true;
        } catch (Exception e) {
            return false;
        }

}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 50, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText(" Producto");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre", "Precio Venta", "Precio Compra", "Cantidad"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        fila = jTable1.getSelectedRow();
        id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        name = jTable1.getValueAt(fila, 1).toString();
        pv = Double.parseDouble(jTable1.getValueAt(fila, 2).toString());
        pc = Double.parseDouble(jTable1.getValueAt(fila, 3).toString());
        cantidad = Integer.parseInt(jTable1.getValueAt(fila, 4).toString());
        System.out.println("ID:"+id+" Nombre "+name+" pv "+pv+" pc "+pc+" cantidad: "+cantidad);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Estas Seguro de eliminar este producto?");
        if(x==0 && id>0){
            if(delete(id)){
                JOptionPane.showMessageDialog(this, "Se elimino");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "No se elimino");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     int x = JOptionPane.showConfirmDialog(this, "Estas Seguro de Modificar este producto?");
     jTable1.clearSelection();
    // jTable1.select
        if(x==0 && id>0){
            System.out.println("ID:"+id+" Nombre "+name+" pv "+pv+" pc "+pc+" cantidad: "+cantidad);
            productoC p = new productoC(id, name, pv, pc, cantidad);
            System.out.println(p.getProducto()+" "+p.getNombre()+" "+p.getPrecioVenta()+" "+p.getPrecioCompra()+" "+p.getCantidad());
            if(update(p)){
                JOptionPane.showMessageDialog(this, "Se actualizo");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "No se actualizo");
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  public ArrayList<productoC> read(){
    conexion c  = new conexion();
    ArrayList<productoC> lista = new ArrayList<>();

      try {
             String sql = "SELECT * FROM producto";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
            productoC p= new productoC(rs.getInt("idProducto"), rs.getString("nombre"), rs.getDouble("precioVenta"), rs.getDouble("precioCompra"), rs.getInt("cantidad"));
            lista.add(p);
            }
            ps.close();
            ps=null;
            c.desconectar();
      } catch (Exception e) {
          System.out.println("Fallo metodo");
      }
      return lista;
  
  
  }
  
  
  public void refresh(){
      while(model.getRowCount()>0){
          model.removeRow(0);
      }
      ArrayList<productoC> lista= read();
      for (productoC p: lista) {
          Object item[]= new Object[5];
          item[0]=p.getProducto();
          item[1]=p.getNombre();
          item[2]=p.getPrecioVenta();
          item[3]=p.getPrecioCompra();
          item[4]=p.getCantidad();
          model.addRow(item);
        
      }
  
        jTable1.setModel(model);
  
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
