/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danielp;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aran
 */
public class sPrestamo extends javax.swing.JFrame {
DefaultComboBoxModel modeloFactura, modeloCliente;
boolean regresar;
boolean confirmar = false;
factura factura;
int prestamos;
Prestamo p;
    /**
     * Creates new form sPrestamo
     */
    public sPrestamo(Prestamo p ) {
        initComponents();
        this.p=p;
        this.setVisible(true);
        this.setTitle("Prestamos");
        refresh();
        jComboBox2.setEnabled(false);
        jButton1.setEnabled(false);
        Total.setText("");
        regresar = false;
        setPrestamo();
        jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        noP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 50, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Prestamo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No Prestamo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No Factura");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Id Cliente");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Total:");

        Total.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Total.setText("-----------------");

        noP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        noP.setText("M");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Autorizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(178, 178, 178)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(noP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Total))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x = JOptionPane.showConfirmDialog(this, "Estas Seguro de Actualizar este Proveedor?");
        if(x==0){
            if(createP(prestamos, factura)){
                JOptionPane.showMessageDialog(this, "Se agrego el prestamo");
                sPrestamo s = new sPrestamo(p);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "No se no se ha seleccionado el prestamo");
            }
        }
        
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object cliente = jComboBox1.getSelectedItem();
        ClienteC c = (ClienteC)cliente;
        getFact(c.getId());
            System.out.println("regresar  "+regresar);
            if(regresar==false){
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(true);
            jButton2.setText("Regresar");
            regresar = true;
            jButton3.setEnabled(true);
            
            

            
            }else{
                jComboBox1.setEnabled(true);
                jComboBox2.setEnabled(false);
                jButton2.setText("Buscar");
                regresar = false;
                int itemCount = jComboBox2.getItemCount();
                for(int i=0;i<itemCount;i++){
                jComboBox2.removeItemAt(0);
                jButton1.setEnabled(false);
                Total.setText("");
                jButton3.setEnabled(false);
             }
            
            }
            
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Object fact = jComboBox2.getSelectedItem();
        factura fa = (factura)fact;
        factura = getFactura(fa.getIdFactura());
        
        System.out.println(" "+factura.getIdFactura()+"  "+factura.getTotal());
        Total.setText(""+factura.getTotal());
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.p.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    public ArrayList<ClienteC> readC(){
        conexion c  = new conexion();
        ArrayList<ClienteC> lista = new ArrayList<>();

          try {
                 String sql = "SELECT * FROM cliente";
                PreparedStatement ps = c.connectDb().prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                ClienteC p =  new  ClienteC(rs.getInt("idCliente"), rs.getString("nombre"), rs.getString("apellido"), rs.getInt("telefono"), rs.getString("direccion"));
                lista.add(p);
                }
                ps.close();
                ps=null;
                c.desconectar();
          } catch (Exception e) {
              System.out.println("Fallo metodo");
          }
          return lista;
  
  
  }
    public factura getFactura(int id){
    
    conexion c  = new conexion();
    try {
           String sql = "SELECT f.idFactura, c.idCliente, f.fecha,sum(p.precioVenta) as Total FROM factura f join cliente c on c.idCliente=f.idCliente join detalle d on d.idfactura=f.idFactura join producto p on d.idproducto=p.idProducto where f.idFactura = "+id+"";
           PreparedStatement ps = c.connectDb().prepareStatement(sql);
           ResultSet rs=ps.executeQuery();
           rs.next();
           factura f =  new  factura(rs.getInt("f.idFactura"), rs.getString("f.fecha"), rs.getInt("c.idCliente"), rs.getFloat("Total"));
           
           ps.close();
           ps=null;
           c.desconectar();
           return f;
          } catch (Exception e) {
              System.out.println("Fallo metodo");
          }
          return null;
    }
    
    public void refresh(){
       
        modeloCliente =(DefaultComboBoxModel)this.jComboBox1.getModel();
        ArrayList<ClienteC> lista= readC();
        for (int i = 0; i < lista.size(); i++) {  
           modeloCliente.addElement(lista.get(i));
           // System.out.println(lista.get(i));
        }
        
        int itemCount = jComboBox2.getItemCount();

        for(int i=0;i<itemCount;i++){
            jComboBox2.removeItemAt(0);
         }

  }
    
    public void getFact(int idCliente){
        modeloFactura =(DefaultComboBoxModel)this.jComboBox2.getModel();
        ArrayList<factura> lista= readf(idCliente);
        for (int i = 0; i < lista.size(); i++) {  
           modeloFactura.addElement(lista.get(i));
           // System.out.println(lista.get(i));
        }
    }
    
    public void setPrestamo(){
        
      conexion c  = new conexion();
           
              try {
                    String sql = "SELECT MAX(idPrestamo) FROM prestamo";
                    PreparedStatement ps = c.connectDb().prepareStatement(sql);
                    ResultSet rs=ps.executeQuery();
                    rs.next();
                    prestamos=rs.getInt("MAX(idPrestamo)")+1;
                    noP.setText(""+prestamos);
                    
                    ps.close();
                    ps=null;
                    c.desconectar();
              } catch (Exception e) {
                  System.out.println("Fallo metodo");
              }
     
     }
    
    public ArrayList<factura> readf(int idCliente){
        conexion c  = new conexion();
        ArrayList<factura> lista = new ArrayList<>();

          try {
                 String sql = "SELECT * FROM factura WHERE idCliente="+idCliente+"";
                PreparedStatement ps = c.connectDb().prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                factura p= new factura(rs.getInt("idFactura"), rs.getString("fecha"), rs.getInt("idCliente"));
                lista.add(p);
                }
                ps.close();
                ps=null;
                c.desconectar();
          } catch (Exception e) {
              System.out.println("Fallo metodo");
          }
          return lista;
    }
    
    
        public boolean createP(int idPrestamo,factura f){
        conexion c= new conexion();
            System.out.println(""+idPrestamo+"idf"+f.getIdFactura()+"  "+f.getDate()+"  "+f.getTotal());
        try {
            String sql="INSERT INTO prestamo(idPrestamo,fecha,idFactura,saldo,monto) VALUES("+idPrestamo+",'"+f.getDate()+"',"+f.getIdFactura()+","+f.getTotal()+","+f.getTotal()+")";
            PreparedStatement ps = c.connectDb().prepareStatement(sql);
            ps.execute();
            ps=null;
            c.desconectar();
            JOptionPane.showMessageDialog(this, "se realizo el prestamo");
            
            return true;
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "no se inserto el registro");
            System.out.println("no se realizo el prestamo");
            return false;
        }
    
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noP;
    // End of variables declaration//GEN-END:variables
}
